# Helper: compute project a covariance / scatter matrix with gips
project_cov_MAP <- function(emp_cov, n_obs) {
    # build gips object from empirical covariance / scatter and n
    gg <- gips::gips(emp_cov, n_obs, was_mean_estimated = TRUE)
    # optimize to find MAP
    gg <- gips::find_MAP(gg, optimizer = "BF")
    perm <- gg[[1]]
    # project matrix onto invariants of cyclic group generated by perm
    gips::project_matrix(emp_cov, perm)
}